# tl;dr We will just run the bentoml->kaniko catalog tasks
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ml-pipeline
  namespace: ce
spec:
  workspaces:
    - name: bentoml
  params:
    - name: servicename
      type: string
      description: The name of the BentoML service you want to build
    - name: serviceversion
      type: string
      description: The version of the BentoML service you want to build
    - name: yataiserviceuri
      type: string
      description: The URI of the BentoML YataiService
      default: ""
    - name: image
      type: string
      description: The image we will build
      default: ""
    - name: production_endpoint
      type: string
      description: The triggers endpoint to send out completion CloudEvent
      default: ""
  tasks:
    - name: bentoml-retrieve
      taskRef:
        name: bentoml
      params:
      - name: YATAISERVICE
        value: $(params.yataiserviceuri)
      - name: ARGS
        value: ["retrieve", "$(params.servicename):$(params.serviceversion)", "--target_dir=$(workspaces.bentoml.path)/$(params.servicename)"]
      workspaces:
      - name: bentoml
        workspace: bentoml
    - name: kaniko-build
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: bentoml
      params:
      - name: IMAGE
        value: $(params.image)
      - name: DOCKERFILE
        value: "/$(workspaces.source.path)/$(params.servicename)/Dockerfile"
      - name: CONTEXT
        value: "$(params.servicename)"
      runAfter:
        - bentoml-retrieve
